/* 청소년 관심 직업 풀 (~500) — 월드컵 남은 칸 채우기용 */
window.YOUTH_JOB_POOL = [
  // 테크·디지털
  { name: "AI 프로덕트 매니저", cat: "테크", emoji: "🤖", color: "#DBEAFE" },
  { name: "AI 엔지니어", cat: "테크", emoji: "🤖", color: "#DBEAFE" },
  { name: "머신러닝 엔지니어", cat: "테크", emoji: "🧠", color: "#E0E7FF" },
  { name: "데이터 사이언티스트", cat: "테크", emoji: "📊", color: "#DBEAFE" },
  { name: "데이터 분석가", cat: "테크", emoji: "📈", color: "#DBEAFE" },
  { name: "빅데이터 엔지니어", cat: "테크", emoji: "💾", color: "#E0F2FE" },
  { name: "프론트엔드 개발자", cat: "테크", emoji: "💻", color: "#E0F2FE" },
  { name: "백엔드 개발자", cat: "테크", emoji: "🖥️", color: "#DBEAFE" },
  { name: "풀스택 개발자", cat: "테크", emoji: "💻", color: "#E0E7FF" },
  { name: "앱 개발자", cat: "테크", emoji: "📱", color: "#DBEAFE" },
  { name: "게임 프로그래머", cat: "테크", emoji: "🎮", color: "#EDE9FE" },
  { name: "게임 기획자", cat: "테크", emoji: "🕹️", color: "#EDE9FE" },
  { name: "로봇 공학자", cat: "테크", emoji: "🦾", color: "#E0E7FF" },
  { name: "사이버보안 전문가", cat: "테크", emoji: "🛡️", color: "#DBEAFE" },
  { name: "클라우드 엔지니어", cat: "테크", emoji: "☁️", color: "#E0F2FE" },
  { name: "DevOps 엔지니어", cat: "테크", emoji: "⚙️", color: "#DBEAFE" },
  { name: "블록체인 개발자", cat: "테크", emoji: "⛓️", color: "#E0E7FF" },
  { name: "VR/AR 개발자", cat: "테크", emoji: "🥽", color: "#EDE9FE" },
  { name: "메타버스 기획자", cat: "테크", emoji: "🌐", color: "#DBEAFE" },
  { name: "IoT 엔지니어", cat: "테크", emoji: "📡", color: "#E0F2FE" },
  { name: "자율주행 엔지니어", cat: "테크", emoji: "🚗", color: "#DBEAFE" },
  { name: "드론 개발자", cat: "테크", emoji: "🚁", color: "#E0E7FF" },
  { name: "반도체 엔지니어", cat: "테크", emoji: "🔋", color: "#DBEAFE" },
  { name: "임베디드 개발자", cat: "테크", emoji: "🔌", color: "#E0F2FE" },
  { name: "정보보안 컨설턴트", cat: "테크", emoji: "🔐", color: "#DBEAFE" },
  { name: "시스템 관리자", cat: "테크", emoji: "🧰", color: "#E0E7FF" },
  { name: "QA 엔지니어", cat: "테크", emoji: "✅", color: "#D1FAE5" },
  { name: "프로덕트 오너", cat: "테크", emoji: "🧩", color: "#E0E7FF" },
  { name: "IT 컨설턴트", cat: "테크", emoji: "💼", color: "#DBEAFE" },
  { name: "테크 스타트업 창업가", cat: "테크", emoji: "🚀", color: "#D1FAE5" },
  { name: "프롬프트 엔지니어", cat: "테크", emoji: "✍️", color: "#EDE9FE" },
  { name: "AI 윤리 전문가", cat: "테크", emoji: "🧭", color: "#DBEAFE" },
  { name: "디지털 포렌식 전문가", cat: "테크", emoji: "🕵️", color: "#E0E7FF" },
  { name: "네트워크 엔지니어", cat: "테크", emoji: "📶", color: "#DBEAFE" },
  { name: "데이터베이스 관리자", cat: "테크", emoji: "🗄️", color: "#E0F2FE" },
  { name: "웹 퍼블리셔", cat: "테크", emoji: "🌐", color: "#DBEAFE" },
  { name: "모바일 UX 엔지니어", cat: "테크", emoji: "📲", color: "#E0E7FF" },
  { name: "음성인식 엔지니어", cat: "테크", emoji: "🎙️", color: "#DBEAFE" },
  { name: "컴퓨터 비전 엔지니어", cat: "테크", emoji: "👁️", color: "#EDE9FE" },
  { name: "양자컴퓨팅 연구원", cat: "테크", emoji: "⚛️", color: "#DBEAFE" },
  { name: "핀테크 개발자", cat: "테크", emoji: "💳", color: "#D1FAE5" },
  { name: "헬스케어 IT 개발자", cat: "테크", emoji: "🏥", color: "#E0F2FE" },
  { name: "스마트팩토리 엔지니어", cat: "테크", emoji: "🏭", color: "#DBEAFE" },
  { name: "소프트웨어 아키텍트", cat: "테크", emoji: "🏛️", color: "#E0E7FF" },
  { name: "오픈소스 기여자", cat: "테크", emoji: "🧩", color: "#DBEAFE" },
  { name: "테크니컬 라이터", cat: "테크", emoji: "📝", color: "#FEF3C7" },
  { name: "IT 강사", cat: "테크", emoji: "👨‍🏫", color: "#FEF3C7" },
  { name: "앱스토어 운영자", cat: "테크", emoji: "🏪", color: "#DBEAFE" },
  { name: "전자상거래 개발자", cat: "테크", emoji: "🛒", color: "#E0F2FE" },
  { name: "검색엔진 최적화 전문가", cat: "테크", emoji: "🔍", color: "#DBEAFE" },
  // 콘텐츠·미디어
  { name: "숏폼 크리에이터", cat: "콘텐츠", emoji: "📱", color: "#FCE7F3" },
  { name: "유튜버", cat: "콘텐츠", emoji: "▶️", color: "#FEE2E2" },
  { name: "웹툰 작가", cat: "콘텐츠", emoji: "🖌️", color: "#FFEDD5" },
  { name: "웹소설 작가", cat: "콘텐츠", emoji: "📖", color: "#FEF3C7" },
  { name: "영상 PD", cat: "콘텐츠", emoji: "🎬", color: "#EDE9FE" },
  { name: "방송 작가", cat: "콘텐츠", emoji: "🖊️", color: "#FEF3C7" },
  { name: "시나리오 작가", cat: "콘텐츠", emoji: "📜", color: "#FFEDD5" },
  { name: "팟캐스트 진행자", cat: "콘텐츠", emoji: "🎧", color: "#EDE9FE" },
  { name: "BJ/스트리머", cat: "콘텐츠", emoji: "🎥", color: "#FCE7F3" },
  { name: "인플루언서", cat: "콘텐츠", emoji: "✨", color: "#FCE7F3" },
  { name: "사진작가", cat: "콘텐츠", emoji: "📷", color: "#DBEAFE" },
  { name: "영상 편집자", cat: "콘텐츠", emoji: "✂️", color: "#EDE9FE" },
  { name: "음향 엔지니어", cat: "콘텐츠", emoji: "🎚️", color: "#E0E7FF" },
  { name: "작곡가", cat: "콘텐츠", emoji: "🎵", color: "#FCE7F3" },
  { name: "가수", cat: "콘텐츠", emoji: "🎤", color: "#FCE7F3" },
  { name: "래퍼", cat: "콘텐츠", emoji: "🎧", color: "#EDE9FE" },
  { name: "성우", cat: "콘텐츠", emoji: "🗣️", color: "#FEF3C7" },
  { name: "배우", cat: "콘텐츠", emoji: "🎭", color: "#FCE7F3" },
  { name: "뮤지컬 배우", cat: "콘텐츠", emoji: "🎭", color: "#EDE9FE" },
  { name: "안무가", cat: "콘텐츠", emoji: "💃", color: "#FCE7F3" },
  { name: "댄스 크리에이터", cat: "콘텐츠", emoji: "🕺", color: "#FCE7F3" },
  { name: "예능 작가", cat: "콘텐츠", emoji: "😂", color: "#FEF3C7" },
  { name: "다큐멘터리 감독자", cat: "콘텐츠", emoji: "🎞️", color: "#DBEAFE" },
  { name: "뉴스 앵커", cat: "콘텐츠", emoji: "📺", color: "#E0F2FE" },
  { name: "기자", cat: "콘텐츠", emoji: "📰", color: "#FEF3C7" },
  { name: "과학 커뮤니케이터", cat: "콘텐츠", emoji: "🔬", color: "#D1FAE5" },
  { name: "북튜버", cat: "콘텐츠", emoji: "📚", color: "#FEF3C7" },
  { name: "게임 스트리머", cat: "콘텐츠", emoji: "🎮", color: "#EDE9FE" },
  { name: "e스포츠 선수", cat: "콘텐츠", emoji: "🏆", color: "#DBEAFE" },
  { name: "e스포츠 캐스터", cat: "콘텐츠", emoji: "🎙️", color: "#E0E7FF" },
  { name: "만화 스토리보드 작가", cat: "콘텐츠", emoji: "📑", color: "#FFEDD5" },
  { name: "애니메이션 감독", cat: "콘텐츠", emoji: "🐰", color: "#FCE7F3" },
  { name: "자막 번역가", cat: "콘텐츠", emoji: "🔤", color: "#DBEAFE" },
  { name: "콘텐츠 기획자", cat: "콘텐츠", emoji: "💡", color: "#FEF3C7" },
  { name: "채널 매니저", cat: "콘텐츠", emoji: "📋", color: "#EDE9FE" },
  { name: "틱톡 마케터", cat: "콘텐츠", emoji: "📲", color: "#FCE7F3" },
  { name: "바이럴 콘텐츠 기획자", cat: "콘텐츠", emoji: "🔥", color: "#FEE2E2" },
  { name: "스토리텔러", cat: "콘텐츠", emoji: "🪄", color: "#EDE9FE" },
  { name: "MCN 기획자", cat: "콘텐츠", emoji: "🏢", color: "#DBEAFE" },
  { name: "공연 연출가", cat: "콘텐츠", emoji: "🎪", color: "#FCE7F3" },
  { name: "무대 조명 디자이너", cat: "콘텐츠", emoji: "💡", color: "#FEF3C7" },
  { name: "영화 촬영감독", cat: "콘텐츠", emoji: "🎥", color: "#E0E7FF" },
  { name: "특수효과 아티스트", cat: "콘텐츠", emoji: "💥", color: "#FEE2E2" },
  { name: "예능 PD", cat: "콘텐츠", emoji: "📺", color: "#FCE7F3" },
  { name: "라디오 PD", cat: "콘텐츠", emoji: "📻", color: "#FEF3C7" },
  { name: "출판 편집자", cat: "콘텐츠", emoji: "📕", color: "#FFEDD5" },
  { name: "동화 작가", cat: "콘텐츠", emoji: "🧚", color: "#FCE7F3" },
  { name: "시인", cat: "콘텐츠", emoji: "🌸", color: "#FCE7F3" },
  { name: "번역가", cat: "콘텐츠", emoji: "🌍", color: "#DBEAFE" },
  { name: "통역사", cat: "콘텐츠", emoji: "🗣️", color: "#E0F2FE" },
  // 디자인
  { name: "UX 디자이너", cat: "디자인", emoji: "✨", color: "#D1FAE5" },
  { name: "UI 디자이너", cat: "디자인", emoji: "🖼️", color: "#DBEAFE" },
  { name: "브랜드 디자이너", cat: "디자인", emoji: "🎨", color: "#FEF3C7" },
  { name: "그래픽 디자이너", cat: "디자인", emoji: "🖌️", color: "#FCE7F3" },
  { name: "패키지 디자이너", cat: "디자인", emoji: "📦", color: "#FFEDD5" },
  { name: "공간 디자이너", cat: "디자인", emoji: "🏠", color: "#DBEAFE" },
  { name: "인테리어 디자이너", cat: "디자인", emoji: "🛋️", color: "#FEF3C7" },
  { name: "패션 디자이너", cat: "디자인", emoji: "👗", color: "#FCE7F3" },
  { name: "산업 디자이너", cat: "디자인", emoji: "🪑", color: "#E0E7FF" },
  { name: "캐릭터 디자이너", cat: "디자인", emoji: "🧸", color: "#FCE7F3" },
  { name: "3D 모델러", cat: "디자인", emoji: "🧊", color: "#DBEAFE" },
  { name: "모션 그래픽 디자이너", cat: "디자인", emoji: "🎞️", color: "#EDE9FE" },
  { name: "타이포그래퍼", cat: "디자인", emoji: "🔤", color: "#FEF3C7" },
  { name: "일러스트레이터", cat: "디자인", emoji: "🖍️", color: "#FFEDD5" },
  { name: "컨셉 아티스트", cat: "디자인", emoji: "🌌", color: "#EDE9FE" },
  { name: "서비스 디자이너", cat: "디자인", emoji: "🗺️", color: "#D1FAE5" },
  { name: "전시 디자이너", cat: "디자인", emoji: "🖼️", color: "#DBEAFE" },
  { name: "무대 디자이너", cat: "디자인", emoji: "🎭", color: "#FCE7F3" },
  { name: "뷰티 메이크업 아티스트", cat: "디자인", emoji: "💄", color: "#FCE7F3" },
  { name: "헤어 디자이너", cat: "디자인", emoji: "💇", color: "#FEF3C7" },
  { name: "네일 아티스트", cat: "디자인", emoji: "💅", color: "#FCE7F3" },
  { name: "주얼리 디자이너", cat: "디자인", emoji: "💎", color: "#E0E7FF" },
  { name: "신발 디자이너", cat: "디자인", emoji: "👟", color: "#DBEAFE" },
  { name: "텍스타일 디자이너", cat: "디자인", emoji: "🧵", color: "#FFEDD5" },
  { name: "자동차 디자이너", cat: "디자인", emoji: "🚘", color: "#DBEAFE" },
  { name: "게임 아트 디렉터", cat: "디자인", emoji: "🎯", color: "#EDE9FE" },
  { name: "UI 리서처", cat: "디자인", emoji: "🔎", color: "#D1FAE5" },
  { name: "디자인 시스템 매니저", cat: "디자인", emoji: "📐", color: "#DBEAFE" },
  { name: "아트 디렉터", cat: "디자인", emoji: "🎬", color: "#FCE7F3" },
  { name: "크리에이티브 디렉터", cat: "디자인", emoji: "💡", color: "#FEF3C7" },
  // 비즈니스·경영
  { name: "콘텐츠 마케터", cat: "비즈니스", emoji: "📣", color: "#FCE7F3" },
  { name: "퍼포먼스 마케터", cat: "비즈니스", emoji: "📊", color: "#DBEAFE" },
  { name: "브랜드 매니저", cat: "비즈니스", emoji: "🏷️", color: "#FEF3C7" },
  { name: "스타트업 창업가", cat: "비즈니스", emoji: "🚀", color: "#D1FAE5" },
  { name: "투자 애널리스트", cat: "비즈니스", emoji: "📈", color: "#DCFCE7" },
  { name: "벤처캐피탈리스트", cat: "비즈니스", emoji: "💰", color: "#FEF3C7" },
  { name: "경영 컨설턴트", cat: "비즈니스", emoji: "📑", color: "#E0E7FF" },
  { name: "경영 전략가", cat: "비즈니스", emoji: "♟️", color: "#DBEAFE" },
  { name: "인사 담당자(HR)", cat: "비즈니스", emoji: "👥", color: "#D1FAE5" },
  { name: "채용 담당자", cat: "비즈니스", emoji: "🤝", color: "#FEF3C7" },
  { name: "회계사", cat: "비즈니스", emoji: "🧮", color: "#DBEAFE" },
  { name: "세무사", cat: "비즈니스", emoji: "🧾", color: "#FEF3C7" },
  { name: "공인중개사", cat: "비즈니스", emoji: "🏡", color: "#FFEDD5" },
  { name: "무역 전문가", cat: "비즈니스", emoji: "🚢", color: "#DBEAFE" },
  { name: "물류 매니저", cat: "비즈니스", emoji: "📦", color: "#E0F2FE" },
  { name: "이커머스 MD", cat: "비즈니스", emoji: "🛍️", color: "#FCE7F3" },
  { name: "바이어", cat: "비즈니스", emoji: "🧾", color: "#FEF3C7" },
  { name: "세일즈 매니저", cat: "비즈니스", emoji: "🗣️", color: "#DBEAFE" },
  { name: "고객 성공 매니저", cat: "비즈니스", emoji: "🤗", color: "#D1FAE5" },
  { name: "PR 전문가", cat: "비즈니스", emoji: "📢", color: "#FCE7F3" },
  { name: "광고 기획자", cat: "비즈니스", emoji: "🪧", color: "#FEF3C7" },
  { name: "카피라이터", cat: "비즈니스", emoji: "✏️", color: "#FFEDD5" },
  { name: "이벤트 플래너", cat: "비즈니스", emoji: "🎉", color: "#FCE7F3" },
  { name: "웨딩 플래너", cat: "비즈니스", emoji: "💒", color: "#FCE7F3" },
  { name: "항공 승무원", cat: "비즈니스", emoji: "✈️", color: "#DBEAFE" },
  { name: "호텔리어", cat: "비즈니스", emoji: "🏨", color: "#FFEDD5" },
  { name: "여행 상품 기획자", cat: "비즈니스", emoji: "🧳", color: "#D1FAE5" },
  { name: "관광 가이드", cat: "비즈니스", emoji: "🗺️", color: "#FEF3C7" },
  { name: "프랜차이즈 창업가", cat: "비즈니스", emoji: "🏪", color: "#FFEDD5" },
  { name: "소셜벤처 창업가", cat: "비즈니스", emoji: "💚", color: "#D1FAE5" },
  { name: "지속가능 컨설턴트", cat: "비즈니스", emoji: "♻️", color: "#D1FAE5" },
  { name: "ESG 전문가", cat: "비즈니스", emoji: "🌿", color: "#DCFCE7" },
  { name: "프로젝트 매니저", cat: "비즈니스", emoji: "📌", color: "#DBEAFE" },
  { name: "오피스 매니저", cat: "비즈니스", emoji: "🗂️", color: "#FEF3C7" },
  { name: "은행원", cat: "비즈니스", emoji: "🏦", color: "#DBEAFE" },
  { name: "펀드매니저", cat: "비즈니스", emoji: "💹", color: "#DCFCE7" },
  { name: "보험 설계사", cat: "비즈니스", emoji: "🛡️", color: "#E0E7FF" },
  { name: "부동산 디벨로퍼", cat: "비즈니스", emoji: "🏗️", color: "#FFEDD5" },
  { name: "유통 기획자", cat: "비즈니스", emoji: "🛒", color: "#DBEAFE" },
  { name: "브랜드 스토리텔러", cat: "비즈니스", emoji: "📖", color: "#FCE7F3" },
  { name: "그로스 해커", cat: "비즈니스", emoji: "📊", color: "#D1FAE5" },
  { name: "커뮤니티 매니저", cat: "비즈니스", emoji: "💬", color: "#EDE9FE" },
  { name: "비즈니스 애널리스트", cat: "비즈니스", emoji: "📉", color: "#DBEAFE" },
  { name: "해외영업 전문가", cat: "비즈니스", emoji: "🌏", color: "#E0F2FE" },
  // 헬스케어
  { name: "의사", cat: "헬스케어", emoji: "🩺", color: "#E0F2FE" },
  { name: "간호사", cat: "헬스케어", emoji: "👩‍⚕️", color: "#FCE7F3" },
  { name: "약사", cat: "헬스케어", emoji: "💊", color: "#D1FAE5" },
  { name: "한의사", cat: "헬스케어", emoji: "🌿", color: "#DCFCE7" },
  { name: "수의사", cat: "헬스케어", emoji: "🐾", color: "#FEF3C7" },
  { name: "임상심리사", cat: "헬스케어", emoji: "🧠", color: "#EDE9FE" },
  { name: "상담심리사", cat: "헬스케어", emoji: "💭", color: "#DBEAFE" },
  { name: "물리치료사", cat: "헬스케어", emoji: "🏃", color: "#D1FAE5" },
  { name: "작업치료사", cat: "헬스케어", emoji: "🤲", color: "#FEF3C7" },
  { name: "언어치료사", cat: "헬스케어", emoji: "🗣️", color: "#E0F2FE" },
  { name: "영양사", cat: "헬스케어", emoji: "🥗", color: "#DCFCE7" },
  { name: "치과의사", cat: "헬스케어", emoji: "🦷", color: "#DBEAFE" },
  { name: "응급구조사", cat: "헬스케어", emoji: "🚑", color: "#FEE2E2" },
  { name: "방사선사", cat: "헬스케어", emoji: "☢️", color: "#E0E7FF" },
  { name: "임상병리사", cat: "헬스케어", emoji: "🔬", color: "#DBEAFE" },
  { name: "안경사", cat: "헬스케어", emoji: "👓", color: "#E0F2FE" },
  { name: "보건교사", cat: "헬스케어", emoji: "🏫", color: "#FEF3C7" },
  { name: "헬스 트레이너", cat: "헬스케어", emoji: "💪", color: "#FEE2E2" },
  { name: "필라테스 강사", cat: "헬스케어", emoji: "🧘", color: "#FCE7F3" },
  { name: "요가 강사", cat: "헬스케어", emoji: "🧘‍♀️", color: "#D1FAE5" },
  { name: "스포츠 재활 전문가", cat: "헬스케어", emoji: "🩹", color: "#FFEDD5" },
  { name: "디지털 헬스케어 기획자", cat: "헬스케어", emoji: "📱", color: "#DBEAFE" },
  { name: "의료 AI 전문가", cat: "헬스케어", emoji: "🤖", color: "#E0E7FF" },
  { name: "공중보건 전문가", cat: "헬스케어", emoji: "🏥", color: "#D1FAE5" },
  { name: "유전상담사", cat: "헬스케어", emoji: "🧬", color: "#EDE9FE" },
  { name: "치위생사", cat: "헬스케어", emoji: "😁", color: "#DBEAFE" },
  { name: "조산사", cat: "헬스케어", emoji: "👶", color: "#FCE7F3" },
  { name: "의료기기 연구원", cat: "헬스케어", emoji: "🛠️", color: "#E0F2FE" },
  { name: "병원 행정가", cat: "헬스케어", emoji: "🗂️", color: "#FEF3C7" },
  { name: "메디컬 일러스트레이터", cat: "헬스케어", emoji: "🖍️", color: "#DBEAFE" },
  // 사이언스·공학
  { name: "환경 엔지니어", cat: "사이언스", emoji: "🌱", color: "#DCFCE7" },
  { name: "우주항공 엔지니어", cat: "사이언스", emoji: "🛰️", color: "#DBEAFE" },
  { name: "생명공학 연구원", cat: "사이언스", emoji: "🧬", color: "#ECFCCB" },
  { name: "기후 데이터 분석가", cat: "사이언스", emoji: "🌍", color: "#CFFAFE" },
  { name: "화학 연구원", cat: "사이언스", emoji: "⚗️", color: "#DBEAFE" },
  { name: "물리학자", cat: "사이언스", emoji: "🔭", color: "#E0E7FF" },
  { name: "수학자", cat: "사이언스", emoji: "➗", color: "#DBEAFE" },
  { name: "통계학자", cat: "사이언스", emoji: "📐", color: "#E0F2FE" },
  { name: "천문학자", cat: "사이언스", emoji: "🌌", color: "#EDE9FE" },
  { name: "지질학자", cat: "사이언스", emoji: "🪨", color: "#FFEDD5" },
  { name: "해양학자", cat: "사이언스", emoji: "🌊", color: "#DBEAFE" },
  { name: "기상예보관", cat: "사이언스", emoji: "⛅", color: "#E0F2FE" },
  { name: "에너지 엔지니어", cat: "사이언스", emoji: "⚡", color: "#FEF3C7" },
  { name: "신재생에너지 전문가", cat: "사이언스", emoji: "☀️", color: "#FEF3C7" },
  { name: "원자력 엔지니어", cat: "사이언스", emoji: "⚛️", color: "#DBEAFE" },
  { name: "건축 엔지니어", cat: "사이언스", emoji: "🏗️", color: "#FFEDD5" },
  { name: "토목 엔지니어", cat: "사이언스", emoji: "🌉", color: "#E0E7FF" },
  { name: "기계 엔지니어", cat: "사이언스", emoji: "⚙️", color: "#DBEAFE" },
  { name: "전기 엔지니어", cat: "사이언스", emoji: "🔌", color: "#FEF3C7" },
  { name: "화학 엔지니어", cat: "사이언스", emoji: "🧪", color: "#D1FAE5" },
  { name: "재료 공학자", cat: "사이언스", emoji: "🧱", color: "#FFEDD5" },
  { name: "식품 연구원", cat: "사이언스", emoji: "🔬", color: "#FEF3C7" },
  { name: "농업 기술자", cat: "사이언스", emoji: "🌾", color: "#DCFCE7" },
  { name: "스마트팜 전문가", cat: "사이언스", emoji: "🏡", color: "#D1FAE5" },
  { name: "바이오의약품 연구원", cat: "사이언스", emoji: "💉", color: "#E0F2FE" },
  { name: "나노기술 연구원", cat: "사이언스", emoji: "🔬", color: "#EDE9FE" },
  { name: "고고학자", cat: "사이언스", emoji: "🏺", color: "#FFEDD5" },
  { name: "인류학자", cat: "사이언스", emoji: "🧭", color: "#FEF3C7" },
  { name: "생태학자", cat: "사이언스", emoji: "🦋", color: "#DCFCE7" },
  { name: "수질 환경 전문가", cat: "사이언스", emoji: "💧", color: "#DBEAFE" },
  { name: "폐기물 자원화 전문가", cat: "사이언스", emoji: "♻️", color: "#D1FAE5" },
  { name: "우주 생물학자", cat: "사이언스", emoji: "👽", color: "#EDE9FE" },
  { name: "드론 측량 전문가", cat: "사이언스", emoji: "📍", color: "#DBEAFE" },
  { name: "지도 제작자", cat: "사이언스", emoji: "🗺️", color: "#D1FAE5" },
  { name: "실험실 연구원", cat: "사이언스", emoji: "🧫", color: "#E0F2FE" },
  // 공공·교육·법
  { name: "교사", cat: "공공·교육", emoji: "📚", color: "#FEF3C7" },
  { name: "유치원 교사", cat: "공공·교육", emoji: "🧒", color: "#FCE7F3" },
  { name: "특수교육 교사", cat: "공공·교육", emoji: "💙", color: "#DBEAFE" },
  { name: "진로진학 상담교사", cat: "공공·교육", emoji: "🧭", color: "#E0E7FF" },
  { name: "대학 교수", cat: "공공·교육", emoji: "🎓", color: "#DBEAFE" },
  { name: "교육 콘텐츠 기획자", cat: "공공·교육", emoji: "🧩", color: "#FEF3C7" },
  { name: "에듀테크 기획자", cat: "공공·교육", emoji: "📱", color: "#D1FAE5" },
  { name: "외교관", cat: "공공·교육", emoji: "🕊️", color: "#DBEAFE" },
  { name: "통번역 공무원", cat: "공공·교육", emoji: "🌐", color: "#E0F2FE" },
  { name: "소방관", cat: "공공·교육", emoji: "🚒", color: "#FEE2E2" },
  { name: "경찰관", cat: "공공·교육", emoji: "🚓", color: "#DBEAFE" },
  { name: "군인", cat: "공공·교육", emoji: "🎖️", color: "#D1FAE5" },
  { name: "변호사", cat: "공공·교육", emoji: "⚖️", color: "#E0E7FF" },
  { name: "검사", cat: "공공·교육", emoji: "⚖️", color: "#DBEAFE" },
  { name: "판사", cat: "공공·교육", emoji: "🧑‍⚖️", color: "#FEF3C7" },
  { name: "변리사", cat: "공공·교육", emoji: "📜", color: "#EDE9FE" },
  { name: "노무사", cat: "공공·교육", emoji: "📋", color: "#DBEAFE" },
  { name: "사회복지사", cat: "공공·교육", emoji: "🤝", color: "#D1FAE5" },
  { name: "청소년 지도사", cat: "공공·교육", emoji: "🌟", color: "#FEF3C7" },
  { name: "사서", cat: "공공·교육", emoji: "📚", color: "#FFEDD5" },
  { name: "박물관 큐레이터", cat: "공공·교육", emoji: "🏛️", color: "#DBEAFE" },
  { name: "기록연구사", cat: "공공·교육", emoji: "🗂️", color: "#E0E7FF" },
  { name: "공무원", cat: "공공·교육", emoji: "🏛️", color: "#FEF3C7" },
  { name: "정책 연구원", cat: "공공·교육", emoji: "📊", color: "#DBEAFE" },
  { name: "국제기구 직원", cat: "공공·교육", emoji: "🌍", color: "#D1FAE5" },
  { name: "NGO 활동가", cat: "공공·교육", emoji: "✊", color: "#FEE2E2" },
  { name: "인권 변호사", cat: "공공·교육", emoji: "🕊️", color: "#E0F2FE" },
  { name: "선거관리 전문가", cat: "공공·교육", emoji: "🗳️", color: "#DBEAFE" },
  { name: "도시 계획가", cat: "공공·교육", emoji: "🏙️", color: "#E0E7FF" },
  { name: "도서관 사서교사", cat: "공공·교육", emoji: "📖", color: "#FEF3C7" },
  { name: "평생교육 강사", cat: "공공·교육", emoji: "🧑‍🏫", color: "#FFEDD5" },
  { name: "진로 코치", cat: "공공·교육", emoji: "🎯", color: "#D1FAE5" },
  { name: "학습 코치", cat: "공공·교육", emoji: "📝", color: "#DBEAFE" },
  { name: "교재 개발자", cat: "공공·교육", emoji: "📘", color: "#FEF3C7" },
  { name: "시험 출제 연구원", cat: "공공·교육", emoji: "❓", color: "#EDE9FE" },
  { name: "교정직 공무원", cat: "공공·교육", emoji: "🔒", color: "#DBEAFE" },
  { name: "세관 공무원", cat: "공공·교육", emoji: "🛃", color: "#E0F2FE" },
  { name: "출입국관리 공무원", cat: "공공·교육", emoji: "🛂", color: "#DBEAFE" },
  // 라이프·서비스·예체능
  { name: "패션 스타일리스트", cat: "라이프", emoji: "👗", color: "#FCE7F3" },
  { name: "스포츠 마케터", cat: "라이프", emoji: "⚽", color: "#D1FAE5" },
  { name: "바리스타 창업가", cat: "라이프", emoji: "☕", color: "#FFEDD5" },
  { name: "셰프", cat: "라이프", emoji: "👨‍🍳", color: "#FEF3C7" },
  { name: "파티시에", cat: "라이프", emoji: "🧁", color: "#FCE7F3" },
  { name: "베이커", cat: "라이프", emoji: "🍞", color: "#FFEDD5" },
  { name: "플로리스트", cat: "라이프", emoji: "💐", color: "#FCE7F3" },
  { name: "반려동물 미용사", cat: "라이프", emoji: "🐶", color: "#FEF3C7" },
  { name: "반려동물 훈련사", cat: "라이프", emoji: "🦮", color: "#D1FAE5" },
  { name: "피트니스 유튜버", cat: "라이프", emoji: "🏋️", color: "#FEE2E2" },
  { name: "프로게이머", cat: "라이프", emoji: "🎮", color: "#EDE9FE" },
  { name: "프로 운동선수", cat: "라이프", emoji: "🏅", color: "#DBEAFE" },
  { name: "스포츠 코치", cat: "라이프", emoji: "📣", color: "#FEF3C7" },
  { name: "심판", cat: "라이프", emoji: "🏁", color: "#E0E7FF" },
  { name: "파일럿", cat: "라이프", emoji: "🛫", color: "#DBEAFE" },
  { name: "항공기 정비사", cat: "라이프", emoji: "🛠️", color: "#E0F2FE" },
  { name: "선장", cat: "라이프", emoji: "⚓", color: "#DBEAFE" },
  { name: "조경사", cat: "라이프", emoji: "🌳", color: "#DCFCE7" },
  { name: "목수", cat: "라이프", emoji: "🪚", color: "#FFEDD5" },
  { name: "도예가", cat: "라이프", emoji: "🏺", color: "#FEF3C7" },
  { name: "공예가", cat: "라이프", emoji: "🧵", color: "#FCE7F3" },
  { name: "메이크업 유튜버", cat: "라이프", emoji: "💋", color: "#FCE7F3" },
  { name: "향수 조향사", cat: "라이프", emoji: "🌸", color: "#FCE7F3" },
  { name: "소믈리에", cat: "라이프", emoji: "🍷", color: "#FEE2E2" },
  { name: "바텐더", cat: "라이프", emoji: "🍸", color: "#EDE9FE" },
  { name: "카페 사장", cat: "라이프", emoji: "☕", color: "#FFEDD5" },
  { name: "식당 창업가", cat: "라이프", emoji: "🍽️", color: "#FEF3C7" },
  { name: "푸드 스타일리스트", cat: "라이프", emoji: "📸", color: "#FCE7F3" },
  { name: "여행 유튜버", cat: "라이프", emoji: "✈️", color: "#DBEAFE" },
  { name: "캠핑 인플루언서", cat: "라이프", emoji: "⛺", color: "#D1FAE5" },
  { name: "자동차 정비사", cat: "라이프", emoji: "🔧", color: "#E0E7FF" },
  { name: "미용사", cat: "라이프", emoji: "💇‍♀️", color: "#FCE7F3" },
  { name: "피부관리사", cat: "라이프", emoji: "✨", color: "#FEF3C7" },
  { name: "마사지 테라피스트", cat: "라이프", emoji: "💆", color: "#D1FAE5" },
  { name: "모델", cat: "라이프", emoji: "🕺", color: "#EDE9FE" },
  { name: "아이돌", cat: "라이프", emoji: "🌟", color: "#FCE7F3" },
  { name: "매니저", cat: "라이프", emoji: "📅", color: "#DBEAFE" },
  { name: "캐스팅 디렉터", cat: "라이프", emoji: "🎬", color: "#FEF3C7" },
  { name: "예체능 학원 강사", cat: "라이프", emoji: "🎨", color: "#FFEDD5" },
  { name: "태권도 사범", cat: "라이프", emoji: "🥋", color: "#FEE2E2" },
  { name: "수영 강사", cat: "라이프", emoji: "🏊", color: "#DBEAFE" },
  { name: "클라이밍 코치", cat: "라이프", emoji: "🧗", color: "#D1FAE5" },
  { name: "서핑 강사", cat: "라이프", emoji: "🏄", color: "#E0F2FE" },
  { name: "자전거 정비사", cat: "라이프", emoji: "🚴", color: "#FEF3C7" },
  { name: "보드게임 카페 사장", cat: "라이프", emoji: "🎲", color: "#EDE9FE" },
  { name: "방탈출 카페 기획자", cat: "라이프", emoji: "🔐", color: "#DBEAFE" },
  { name: "테마파크 기획자", cat: "라이프", emoji: "🎢", color: "#FCE7F3" },
  { name: "레고 아티스트", cat: "라이프", emoji: "🧱", color: "#FEE2E2" },
  { name: "장난감 디자이너", cat: "라이프", emoji: "🧸", color: "#FEF3C7" },
  { name: "유튜브 편집자", cat: "라이프", emoji: "🖥️", color: "#EDE9FE" },
  { name: "라이브 커머스 쇼호스트", cat: "라이프", emoji: "🛍️", color: "#FCE7F3" },
  { name: "중고거래 큐레이터", cat: "라이프", emoji: "♻️", color: "#D1FAE5" },
  { name: "리셀러", cat: "라이프", emoji: "👟", color: "#DBEAFE" },
  { name: "빈티지 숍 운영자", cat: "라이프", emoji: "🧥", color: "#FFEDD5" },
  { name: "플라워 카페 사장", cat: "라이프", emoji: "🌷", color: "#FCE7F3" },
  { name: "북카페 사장", cat: "라이프", emoji: "📖", color: "#FEF3C7" },
  { name: "스터디카페 운영자", cat: "라이프", emoji: "☕", color: "#DBEAFE" },
  { name: "공유오피스 매니저", cat: "라이프", emoji: "🏢", color: "#E0E7FF" },
  { name: "홈케어 전문가", cat: "라이프", emoji: "🧹", color: "#D1FAE5" },
  { name: "정리수납 전문가", cat: "라이프", emoji: "📦", color: "#FEF3C7" },
  { name: "인테리어 시공자", cat: "라이프", emoji: "🛠️", color: "#FFEDD5" },
  { name: "전기 기사", cat: "라이프", emoji: "⚡", color: "#FEF3C7" },
  { name: "배관공", cat: "라이프", emoji: "🔧", color: "#DBEAFE" },
  { name: "용접공", cat: "라이프", emoji: "🔥", color: "#FEE2E2" },
  { name: "택배 기사", cat: "라이프", emoji: "🚚", color: "#E0F2FE" },
  { name: "배달 플랫폼 운영자", cat: "라이프", emoji: "🛵", color: "#DBEAFE" },
  { name: "퀵서비스 창업가", cat: "라이프", emoji: "📦", color: "#FEF3C7" },
  { name: "물류센터 관리자", cat: "라이프", emoji: "🏭", color: "#E0E7FF" },
  { name: "콜센터 관리자", cat: "라이프", emoji: "☎️", color: "#DBEAFE" },
  { name: "고객센터 상담원", cat: "라이프", emoji: "🎧", color: "#D1FAE5" },
  // 추가 트렌드·융합
  { name: "기후테크 창업가", cat: "사이언스", emoji: "🌡️", color: "#DCFCE7" },
  { name: "푸드테크 창업가", cat: "비즈니스", emoji: "🧪", color: "#FEF3C7" },
  { name: "에듀테크 창업가", cat: "테크", emoji: "🚀", color: "#DBEAFE" },
  { name: "헬스테크 창업가", cat: "헬스케어", emoji: "❤️", color: "#FEE2E2" },
  { name: "스페이스테크 엔지니어", cat: "사이언스", emoji: "🚀", color: "#E0E7FF" },
  { name: "배터리 엔지니어", cat: "사이언스", emoji: "🔋", color: "#D1FAE5" },
  { name: "수소에너지 전문가", cat: "사이언스", emoji: "💧", color: "#DBEAFE" },
  { name: "탄소중립 컨설턴트", cat: "비즈니스", emoji: "🌳", color: "#DCFCE7" },
  { name: "도시농업가", cat: "사이언스", emoji: "🥬", color: "#D1FAE5" },
  { name: "수중 로봇 엔지니어", cat: "테크", emoji: "🐠", color: "#DBEAFE" },
  { name: "웨어러블 기기 개발자", cat: "테크", emoji: "⌚", color: "#E0E7FF" },
  { name: "스마트홈 기획자", cat: "테크", emoji: "🏠", color: "#FEF3C7" },
  { name: "디지털 트윈 엔지니어", cat: "테크", emoji: "🧬", color: "#DBEAFE" },
  { name: "생성형 AI 아티스트", cat: "디자인", emoji: "🎨", color: "#EDE9FE" },
  { name: "AI 음성 성우", cat: "콘텐츠", emoji: "🔊", color: "#FCE7F3" },
  { name: "가상인간 기획자", cat: "콘텐츠", emoji: "🧑‍💻", color: "#DBEAFE" },
  { name: "버추얼 아이돌 제작자", cat: "콘텐츠", emoji: "💿", color: "#FCE7F3" },
  { name: "NFT 아티스트", cat: "디자인", emoji: "🖼️", color: "#EDE9FE" },
  { name: "웹3 커뮤니티 매니저", cat: "비즈니스", emoji: "🌐", color: "#DBEAFE" },
  { name: "크립토 애널리스트", cat: "비즈니스", emoji: "🪙", color: "#FEF3C7" },
  { name: "디지털 노마드 컨설턴트", cat: "비즈니스", emoji: "💻", color: "#D1FAE5" },
  { name: "원격근무 코치", cat: "비즈니스", emoji: "🏡", color: "#DBEAFE" },
  { name: "개인 브랜딩 컨설턴트", cat: "비즈니스", emoji: "✨", color: "#FCE7F3" },
  { name: "라이프스타일 큐레이터", cat: "라이프", emoji: "🧺", color: "#FEF3C7" },
  { name: "미니멀 라이프 코치", cat: "라이프", emoji: "🤍", color: "#E0E7FF" },
  { name: "슬립 테크 전문가", cat: "헬스케어", emoji: "😴", color: "#DBEAFE" },
  { name: "멘탈헬스 앱 기획자", cat: "헬스케어", emoji: "💚", color: "#D1FAE5" },
  { name: "청소년 멘토", cat: "공공·교육", emoji: "🌱", color: "#DCFCE7" },
  { name: "진로 유튜버", cat: "콘텐츠", emoji: "🎯", color: "#FEF3C7" },
  { name: "입시 컨설턴트", cat: "공공·교육", emoji: "📝", color: "#DBEAFE" },
  { name: "유학 컨설턴트", cat: "공공·교육", emoji: "✈️", color: "#E0F2FE" },
  { name: "어학원 강사", cat: "공공·교육", emoji: "🗣️", color: "#FEF3C7" },
  { name: "코딩 학원 강사", cat: "테크", emoji: "👨‍💻", color: "#DBEAFE" },
  { name: "로봇 코딩 강사", cat: "테크", emoji: "🤖", color: "#E0E7FF" },
  { name: "과학 실험 강사", cat: "사이언스", emoji: "🔬", color: "#D1FAE5" },
  { name: "미술관 도슨트", cat: "공공·교육", emoji: "🖼️", color: "#FCE7F3" },
  { name: "전시 기획자", cat: "디자인", emoji: "🎟️", color: "#FEF3C7" },
  { name: "축제기획자", cat: "비즈니스", emoji: "🎊", color: "#FCE7F3" },
  { name: "스포츠 에이전트", cat: "라이프", emoji: "🤝", color: "#DBEAFE" },
  { name: "연예 매니저", cat: "라이프", emoji: "📱", color: "#FCE7F3" },
  { name: "공연 프로듀서", cat: "콘텐츠", emoji: "🎶", color: "#EDE9FE" },
  { name: "음원 프로듀서", cat: "콘텐츠", emoji: "🎛️", color: "#DBEAFE" },
  { name: "작사가", cat: "콘텐츠", emoji: "📝", color: "#FEF3C7" },
  { name: "비트메이커", cat: "콘텐츠", emoji: "🥁", color: "#EDE9FE" },
  { name: "DJ", cat: "콘텐츠", emoji: "🎧", color: "#FCE7F3" },
  { name: "사운드 디자이너", cat: "콘텐츠", emoji: "🔊", color: "#E0E7FF" },
  { name: "게임 사운드 디자이너", cat: "테크", emoji: "🎵", color: "#DBEAFE" },
  { name: "레벨 디자이너", cat: "테크", emoji: "🗺️", color: "#EDE9FE" },
  { name: "게임 QA 테스터", cat: "테크", emoji: "🧪", color: "#D1FAE5" },
  { name: "인디 게임 개발자", cat: "테크", emoji: "👾", color: "#EDE9FE" },
  { name: "보드게임 디자이너", cat: "디자인", emoji: "🃏", color: "#FEF3C7" },
  { name: "퍼즐 출제자", cat: "콘텐츠", emoji: "🧩", color: "#DBEAFE" },
  { name: "퀴즈 작가", cat: "콘텐츠", emoji: "❓", color: "#FEF3C7" },
  { name: "예능 출연자", cat: "콘텐츠", emoji: "😄", color: "#FCE7F3" },
  { name: "코미디언", cat: "콘텐츠", emoji: "😂", color: "#FEF3C7" },
  { name: "마술사", cat: "라이프", emoji: "🪄", color: "#EDE9FE" },
  { name: "마임 아티스트", cat: "라이프", emoji: "🎭", color: "#FCE7F3" },
  { name: "서커스 아티스트", cat: "라이프", emoji: "🎪", color: "#FEE2E2" },
  { name: "거리 공연 아티스트", cat: "라이프", emoji: "🎸", color: "#FFEDD5" },
  { name: "버스킹 아티스트", cat: "라이프", emoji: "🎤", color: "#FCE7F3" },
  { name: "캘리그래퍼", cat: "디자인", emoji: "✒️", color: "#FEF3C7" },
  { name: "타투 아티스트", cat: "디자인", emoji: "🖋️", color: "#EDE9FE" },
  { name: "그래피티 아티스트", cat: "디자인", emoji: "🎨", color: "#DBEAFE" },
  { name: "벽화 작가", cat: "디자인", emoji: "🧱", color: "#FFEDD5" },
  { name: "설치미술가", cat: "디자인", emoji: "🗿", color: "#E0E7FF" },
  { name: "미디어아트 작가", cat: "디자인", emoji: "📺", color: "#DBEAFE" },
  { name: "인터랙티브 아티스트", cat: "디자인", emoji: "👆", color: "#EDE9FE" },
  { name: "문화재 복원가", cat: "공공·교육", emoji: "🏺", color: "#FFEDD5" },
  { name: "고서 복원가", cat: "공공·교육", emoji: "📜", color: "#FEF3C7" },
  { name: "전통 공예가", cat: "라이프", emoji: "🪡", color: "#FFEDD5" },
  { name: "한복 디자이너", cat: "디자인", emoji: "👘", color: "#FCE7F3" },
  { name: "전통 음식 연구가", cat: "라이프", emoji: "🍲", color: "#FEF3C7" },
  { name: "발효식품 전문가", cat: "사이언스", emoji: "🫙", color: "#D1FAE5" },
  { name: "커피 로스터", cat: "라이프", emoji: "☕", color: "#FFEDD5" },
  { name: "티 소믈리에", cat: "라이프", emoji: "🍵", color: "#DCFCE7" },
  { name: "초콜릿 장인", cat: "라이프", emoji: "🍫", color: "#FEF3C7" },
  { name: "아이스크림 장인", cat: "라이프", emoji: "🍦", color: "#FCE7F3" },
  { name: "푸드트럭 창업가", cat: "라이프", emoji: "🚚", color: "#FEE2E2" },
  { name: "급식 영양사", cat: "헬스케어", emoji: "🍱", color: "#FEF3C7" },
  { name: "임상 영양사", cat: "헬스케어", emoji: "🥗", color: "#D1FAE5" },
  { name: "스포츠 영양사", cat: "헬스케어", emoji: "🥤", color: "#DBEAFE" },
  { name: "한식 세계화 기획자", cat: "비즈니스", emoji: "🇰🇷", color: "#FEE2E2" },
  { name: "K-컬처 마케터", cat: "비즈니스", emoji: "🌟", color: "#FCE7F3" },
  { name: "한류 콘텐츠 기획자", cat: "콘텐츠", emoji: "📺", color: "#EDE9FE" },
  { name: "관광 콘텐츠 크리에이터", cat: "콘텐츠", emoji: "📸", color: "#DBEAFE" },
  { name: "로컬 크리에이터", cat: "콘텐츠", emoji: "🏘️", color: "#D1FAE5" },
  { name: "마을 기획자", cat: "공공·교육", emoji: "🏡", color: "#FEF3C7" },
  { name: "사회적 기업가", cat: "비즈니스", emoji: "🤝", color: "#DCFCE7" },
  { name: "협동조합 운영자", cat: "비즈니스", emoji: "🔄", color: "#DBEAFE" },
  { name: "공정무역 전문가", cat: "비즈니스", emoji: "⚖️", color: "#D1FAE5" },
  { name: "기부·모금 전문가", cat: "공공·교육", emoji: "💝", color: "#FCE7F3" },
  { name: "자원봉사 코디네이터", cat: "공공·교육", emoji: "🙌", color: "#FEF3C7" },
  { name: "재난 안전 전문가", cat: "공공·교육", emoji: "🚨", color: "#FEE2E2" },
  { name: "사이버수사관", cat: "공공·교육", emoji: "🕵️", color: "#DBEAFE" },
  { name: "과학수사관", cat: "사이언스", emoji: "🔍", color: "#E0E7FF" },
  { name: "해양경찰", cat: "공공·교육", emoji: "🚤", color: "#DBEAFE" },
  { name: "산림청 공무원", cat: "공공·교육", emoji: "🌲", color: "#DCFCE7" },
  { name: "기상청 연구원", cat: "사이언스", emoji: "🌦️", color: "#E0F2FE" },
  { name: "특허 심사관", cat: "공공·교육", emoji: "📜", color: "#FEF3C7" },
  { name: "표준 인증 전문가", cat: "비즈니스", emoji: "✅", color: "#D1FAE5" },
  { name: "품질관리 전문가", cat: "비즈니스", emoji: "📏", color: "#DBEAFE" },
  { name: "물류 데이터 분석가", cat: "테크", emoji: "📦", color: "#E0F2FE" },
  { name: "스마트시티 기획자", cat: "테크", emoji: "🏙️", color: "#DBEAFE" },
  { name: "모빌리티 서비스 기획자", cat: "비즈니스", emoji: "🚕", color: "#FEF3C7" },
  { name: "공유경제 기획자", cat: "비즈니스", emoji: "🔁", color: "#D1FAE5" },
  { name: "구독경제 기획자", cat: "비즈니스", emoji: "📦", color: "#EDE9FE" },
  { name: "리테일 테크 기획자", cat: "테크", emoji: "🛒", color: "#DBEAFE" },
  { name: "옴니채널 마케터", cat: "비즈니스", emoji: "🔗", color: "#FCE7F3" },
  { name: "CRM 전문가", cat: "비즈니스", emoji: "📇", color: "#DBEAFE" },
  { name: "데이터 마케터", cat: "비즈니스", emoji: "📉", color: "#E0E7FF" },
  { name: "그로스 마케터", cat: "비즈니스", emoji: "🚀", color: "#D1FAE5" },
  { name: "인플루언서 마케터", cat: "비즈니스", emoji: "📸", color: "#FCE7F3" },
  { name: "브랜드 경험리언스", cat: "비즈니스", emoji: "🤝", color: "#FEF3C7" },
  { name: "스폰서십 매니저", cat: "비즈니스", emoji: "🏅", color: "#DBEAFE" },
  { name: "팬덤 매니저", cat: "콘텐츠", emoji: "💖", color: "#FCE7F3" },
  { name: "덕질 콘텐츠 기획자", cat: "콘텐츠", emoji: "⭐", color: "#EDE9FE" },
  { name: "굿즈 디자이너", cat: "디자인", emoji: "🎁", color: "#FEF3C7" },
  { name: "팝업스토어 기획자", cat: "비즈니스", emoji: "🏪", color: "#FFEDD5" },
  { name: "전시 공간 큐레이터", cat: "디자인", emoji: "🖼️", color: "#DBEAFE" },
  { name: "아트 딜러", cat: "비즈니스", emoji: "💎", color: "#EDE9FE" },
  { name: "갤러리 디렉터", cat: "디자인", emoji: "🏛️", color: "#FEF3C7" },
  { name: "미술 치료사", cat: "헬스케어", emoji: "🎨", color: "#FCE7F3" },
  { name: "음악 치료사", cat: "헬스케어", emoji: "🎶", color: "#EDE9FE" },
  { name: "놀이 치료사", cat: "헬스케어", emoji: "🧸", color: "#FEF3C7" },
  { name: "드라마 치료사", cat: "헬스케어", emoji: "🎭", color: "#DBEAFE" },
  { name: "동물매개치료사", cat: "헬스케어", emoji: "🐕", color: "#D1FAE5" },
  { name: "숲해설가", cat: "공공·교육", emoji: "🌲", color: "#DCFCE7" },
  { name: "생태관광 가이드", cat: "라이프", emoji: "🥾", color: "#D1FAE5" },
  { name: "국립공원 관리자", cat: "공공·교육", emoji: "🏞️", color: "#DBEAFE" },
  { name: "동물원 사육사", cat: "사이언스", emoji: "🦁", color: "#FEF3C7" },
  { name: "수족관 큐레이터", cat: "사이언스", emoji: "🐠", color: "#E0F2FE" },
  { name: "야생동물 구조사", cat: "사이언스", emoji: "🦅", color: "#DCFCE7" },
  { name: "곤충학자", cat: "사이언스", emoji: "🪲", color: "#D1FAE5" },
  { name: "식물학자", cat: "사이언스", emoji: "🌺", color: "#FCE7F3" },
  { name: "양봉가", cat: "라이프", emoji: "🐝", color: "#FEF3C7" },
  { name: "버섯 재배 전문가", cat: "사이언스", emoji: "🍄", color: "#FFEDD5" },
  { name: "와인 생산자", cat: "라이프", emoji: "🍇", color: "#FCE7F3" },
  { name: "치즈 장인", cat: "라이프", emoji: "🧀", color: "#FEF3C7" },
  { name: "수제맥주 양조사", cat: "라이프", emoji: "🍺", color: "#FFEDD5" },
  { name: "전통주 명인", cat: "라이프", emoji: "🍶", color: "#FEF3C7" },
  { name: "한지 공예가", cat: "디자인", emoji: "📜", color: "#FFEDD5" },
  { name: "금속공예가", cat: "디자인", emoji: "⚒️", color: "#E0E7FF" },
  { name: "목공예가", cat: "디자인", emoji: "🪵", color: "#FFEDD5" },
  { name: "유리공예가", cat: "디자인", emoji: "🔮", color: "#DBEAFE" },
  { name: "도자기 디자이너", cat: "디자인", emoji: "🫖", color: "#FEF3C7" },
  { name: "가구 디자이너", cat: "디자인", emoji: "🪑", color: "#FFEDD5" },
  { name: "조명 디자이너", cat: "디자인", emoji: "💡", color: "#FEF3C7" },
  { name: "사이니지 디자이너", cat: "디자인", emoji: "🪧", color: "#DBEAFE" },
  { name: "키오스크 UI 디자이너", cat: "디자인", emoji: "🖥️", color: "#E0E7FF" },
  { name: "자동차 UX 디자이너", cat: "디자인", emoji: "🚗", color: "#DBEAFE" },
  { name: "의료기기 UX 디자이너", cat: "디자인", emoji: "🏥", color: "#D1FAE5" },
  { name: "접근성 전문가", cat: "테크", emoji: "♿", color: "#DBEAFE" },
  { name: "디지털 포용 전문가", cat: "공공·교육", emoji: "🤝", color: "#D1FAE5" },
  { name: "고령친화 서비스 기획자", cat: "헬스케어", emoji: "🧓", color: "#FEF3C7" },
  { name: "유니버설 디자인 전문가", cat: "디자인", emoji: "♿", color: "#E0E7FF" },
  { name: "다문화 교육 전문가", cat: "공공·교육", emoji: "🌍", color: "#DBEAFE" },
  { name: "한국어 교사", cat: "공공·교육", emoji: "🇰🇷", color: "#FEE2E2" },
  { name: "영어 교사", cat: "공공·교육", emoji: "🔤", color: "#DBEAFE" },
  { name: "일본어 교사", cat: "공공·교육", emoji: "🇯🇵", color: "#FCE7F3" },
  { name: "중국어 교사", cat: "공공·교육", emoji: "🇨🇳", color: "#FEE2E2" },
  { name: "수학 학원 강사", cat: "공공·교육", emoji: "➗", color: "#DBEAFE" },
  { name: "과학 학원 강사", cat: "공공·교육", emoji: "🔬", color: "#D1FAE5" },
  { name: "논술 강사", cat: "공공·교육", emoji: "✍️", color: "#FEF3C7" },
  { name: "면접 코치", cat: "공공·교육", emoji: "🎤", color: "#EDE9FE" },
  { name: "자소서 컨설턴트", cat: "공공·교육", emoji: "📄", color: "#DBEAFE" },
  { name: "포트폴리오 컨설턴트", cat: "디자인", emoji: "🗂️", color: "#FEF3C7" },
  { name: "취업 컨설턴트", cat: "비즈니스", emoji: "💼", color: "#DBEAFE" },
  { name: "헤드헌터", cat: "비즈니스", emoji: "🎯", color: "#E0E7FF" },
  { name: "조직문화 컨설턴트", cat: "비즈니스", emoji: "🏢", color: "#D1FAE5" },
  { name: "변화관리 컨설턴트", cat: "비즈니스", emoji: "🔄", color: "#FEF3C7" },
  { name: "리더십 코치", cat: "비즈니스", emoji: "👑", color: "#FEF3C7" },
  { name: "팀빌딩 퍼실리테이터", cat: "비즈니스", emoji: "🫂", color: "#DBEAFE" },
  { name: "워크숍 디자이너", cat: "디자인", emoji: "🧠", color: "#EDE9FE" },
  { name: "디자인 씽킹 퍼실리테이터", cat: "디자인", emoji: "💡", color: "#FEF3C7" },
  { name: "서비스 블루프린트 전문가", cat: "디자인", emoji: "🗺️", color: "#DBEAFE" },
  { name: "고객 여정 분석가", cat: "비즈니스", emoji: "🧭", color: "#D1FAE5" },
  { name: "보이스 UX 디자이너", cat: "디자인", emoji: "🗣️", color: "#E0E7FF" },
  { name: "챗봇 기획자", cat: "테크", emoji: "💬", color: "#DBEAFE" },
  { name: "대화형 AI 트레이너", cat: "테크", emoji: "🧠", color: "#EDE9FE" },
  { name: "데이터 라벨러 매니저", cat: "테크", emoji: "🏷️", color: "#FEF3C7" },
  { name: "MLOps 엔지니어", cat: "테크", emoji: "⚙️", color: "#DBEAFE" },
  { name: "LLM 애플리케이션 개발자", cat: "테크", emoji: "🧩", color: "#E0E7FF" },
  { name: "AI 안전 연구원", cat: "테크", emoji: "🛡️", color: "#D1FAE5" },
  { name: "로보틱스 연구원", cat: "사이언스", emoji: "🤖", color: "#DBEAFE" },
  { name: "휴머노이드 로봇 엔지니어", cat: "테크", emoji: "🦾", color: "#E0E7FF" },
  { name: "뇌-컴퓨터 인터페이스 연구원", cat: "사이언스", emoji: "🧠", color: "#EDE9FE" },
  { name: "생체인식 전문가", cat: "테크", emoji: "👆", color: "#DBEAFE" }
];
